{
  0:[" politics", " world", " government"], 
  1:[" sports", " competition", " games", " tournament"], 
  2:[" business", " corporation", " enterprise"], 
  3:[" technology", " science", " electronics", " computer", " robotics", " automation"]
}